version: "3.7"

services:
  web:
    build: .
    ports:
      - 8081:80

  mysql:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - todo-mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d
     
    environment: 
      MYSQL_ROOT_PASSWORD: pass@123
      MYSQL_DATABASE: otrs
      MYSQL_USER: otrs
      MYSQL_PASSWORD: otrs

volumes:
  todo-mysql-data: